=== tuscanmoon/XML-Course-Work-1/linearEquation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="linearEquation">
        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="LHS" type="matrix"> </xs:element>
            <xs:element name="RHS" type="vector"> </xs:element>
        </xs:sequence>
    </xs:complexType>
   <xs:complexType name="matrix">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="row" type="vector"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="vector">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="entry" type="number"> </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="number">
        <xs:attribute name="value" type="xs:double"> </xs:attribute>
    </xs:complexType>
    <xs:element name="linearEquation" type="linearEquation">
        
    </xs:element>
</xs:schema>

=== tuscanmoon/XML-Course-Work-1/eqtest6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Student ID: 089583717 -->
<linearEquation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="linearEquation.xsd">
    <LHS>
        <row>
            <entry value="1"/>
            <entry value="2"/>
            <entry value="0"/>
        </row>
        <row>
            <entry value="3"/>
            <entry value="4"/>
            <entry value="4"/>
        </row>
        <row>
            <entry value="5"/>
            <entry value="6"/>
            <entry value="3"/>
        </row>        
    </LHS>
    <RHS>
        <entry value="3"/>
        <entry value="7"/>
    </RHS>
</linearEquation>

=== tuscanmoon/XML-Course-Work-1/eqpass2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Student ID: 089583717 -->
<linearEquation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="linearEquation.xsd">
    <LHS>
        <row>
            <entry value="0.0"/>
            <entry value="1.0"/>
        </row>
        <row>
            <entry value="1.0"/>
            <entry value="2.0"/>
        </row>
   </LHS>
    <RHS>
        <entry value="5.3"/>
        <entry value="2.8"/>
    </RHS>
</linearEquation>
